# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://maxep.github.io/
title: Maxime Epain
email: maxime.epain@gmail.com
description: "I'm an iOS developer based in Paris. In this portfolio you will find several projects I've worked on."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/MaximeEpain
  - title: github
    url: https://github.com/maxep
  - title: linkedin
    url: https://fr.linkedin.com/in/maximeepain

analytics :
    provider : google 
    google : 
        tracking_id : 'UA-61988519-1'
